<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>     
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Bootstrap_Website</AssemblyName>
    <RootNamespace>Bootstrap_Website</RootNamespace>
  </PropertyGroup>

</Project>
